// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gossip.proto

package internal

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Peer struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{0}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Peer) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type JoinRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Laddr                string   `protobuf:"bytes,2,opt,name=laddr,proto3" json:"laddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{1}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *JoinRequest) GetLaddr() string {
	if m != nil {
		return m.Laddr
	}
	return ""
}

type JoinResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Peers                []*Peer  `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{2}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *JoinResponse) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type UnjoinRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnjoinRequest) Reset()         { *m = UnjoinRequest{} }
func (m *UnjoinRequest) String() string { return proto.CompactTextString(m) }
func (*UnjoinRequest) ProtoMessage()    {}
func (*UnjoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{3}
}

func (m *UnjoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnjoinRequest.Unmarshal(m, b)
}
func (m *UnjoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnjoinRequest.Marshal(b, m, deterministic)
}
func (m *UnjoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnjoinRequest.Merge(m, src)
}
func (m *UnjoinRequest) XXX_Size() int {
	return xxx_messageInfo_UnjoinRequest.Size(m)
}
func (m *UnjoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnjoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnjoinRequest proto.InternalMessageInfo

func (m *UnjoinRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UnjoinResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnjoinResponse) Reset()         { *m = UnjoinResponse{} }
func (m *UnjoinResponse) String() string { return proto.CompactTextString(m) }
func (*UnjoinResponse) ProtoMessage()    {}
func (*UnjoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{4}
}

func (m *UnjoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnjoinResponse.Unmarshal(m, b)
}
func (m *UnjoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnjoinResponse.Marshal(b, m, deterministic)
}
func (m *UnjoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnjoinResponse.Merge(m, src)
}
func (m *UnjoinResponse) XXX_Size() int {
	return xxx_messageInfo_UnjoinResponse.Size(m)
}
func (m *UnjoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnjoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnjoinResponse proto.InternalMessageInfo

type PingRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Laddr                string   `protobuf:"bytes,2,opt,name=laddr,proto3" json:"laddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{5}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PingRequest) GetLaddr() string {
	if m != nil {
		return m.Laddr
	}
	return ""
}

type PingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{6}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type WriteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Msg                  []byte   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{7}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WriteRequest) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type WriteResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{8}
}

func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (m *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(m, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

func (m *WriteResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type EraseRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EraseRequest) Reset()         { *m = EraseRequest{} }
func (m *EraseRequest) String() string { return proto.CompactTextString(m) }
func (*EraseRequest) ProtoMessage()    {}
func (*EraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{9}
}

func (m *EraseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EraseRequest.Unmarshal(m, b)
}
func (m *EraseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EraseRequest.Marshal(b, m, deterministic)
}
func (m *EraseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EraseRequest.Merge(m, src)
}
func (m *EraseRequest) XXX_Size() int {
	return xxx_messageInfo_EraseRequest.Size(m)
}
func (m *EraseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EraseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EraseRequest proto.InternalMessageInfo

func (m *EraseRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type EraseResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EraseResponse) Reset()         { *m = EraseResponse{} }
func (m *EraseResponse) String() string { return proto.CompactTextString(m) }
func (*EraseResponse) ProtoMessage()    {}
func (*EraseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_878fa4887b90140c, []int{10}
}

func (m *EraseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EraseResponse.Unmarshal(m, b)
}
func (m *EraseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EraseResponse.Marshal(b, m, deterministic)
}
func (m *EraseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EraseResponse.Merge(m, src)
}
func (m *EraseResponse) XXX_Size() int {
	return xxx_messageInfo_EraseResponse.Size(m)
}
func (m *EraseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EraseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EraseResponse proto.InternalMessageInfo

func (m *EraseResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*Peer)(nil), "internal.Peer")
	proto.RegisterType((*JoinRequest)(nil), "internal.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "internal.JoinResponse")
	proto.RegisterType((*UnjoinRequest)(nil), "internal.UnjoinRequest")
	proto.RegisterType((*UnjoinResponse)(nil), "internal.UnjoinResponse")
	proto.RegisterType((*PingRequest)(nil), "internal.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "internal.PingResponse")
	proto.RegisterType((*WriteRequest)(nil), "internal.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "internal.WriteResponse")
	proto.RegisterType((*EraseRequest)(nil), "internal.EraseRequest")
	proto.RegisterType((*EraseResponse)(nil), "internal.EraseResponse")
}

func init() { proto.RegisterFile("gossip.proto", fileDescriptor_878fa4887b90140c) }

var fileDescriptor_878fa4887b90140c = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdb, 0xe6, 0x0f, 0x3a, 0x5d, 0x43, 0x58, 0xd4, 0x86, 0x9c, 0xe2, 0xe2, 0xa1, 0x07,
	0xc9, 0x21, 0x22, 0x05, 0xc1, 0xa3, 0x0a, 0x9e, 0x4a, 0x40, 0x3c, 0x47, 0xba, 0x84, 0x68, 0xdd,
	0xc4, 0xdd, 0x78, 0xf0, 0x63, 0xf9, 0x0d, 0x65, 0x77, 0x53, 0x3b, 0xb1, 0x8d, 0xe0, 0x6d, 0x32,
	0x3b, 0xef, 0xcd, 0xdb, 0xdf, 0x12, 0x20, 0x65, 0xad, 0x54, 0xd5, 0xa4, 0x8d, 0xac, 0xdb, 0x9a,
	0x1e, 0x54, 0xa2, 0xe5, 0x52, 0x14, 0x6b, 0x76, 0x01, 0xee, 0x92, 0x73, 0x49, 0x43, 0x70, 0x5e,
	0xf9, 0x67, 0x34, 0x4e, 0xc6, 0xf3, 0xc3, 0x5c, 0x97, 0x94, 0x82, 0x5b, 0xac, 0x56, 0x32, 0x9a,
	0x98, 0x96, 0xa9, 0xd9, 0x15, 0x4c, 0x1f, 0xea, 0x4a, 0xe4, 0xfc, 0xfd, 0x83, 0xab, 0x76, 0x8f,
	0xe8, 0x18, 0xbc, 0x35, 0x52, 0xd9, 0x0f, 0x76, 0x07, 0xc4, 0xca, 0x54, 0x53, 0x0b, 0xc5, 0xf7,
	0xe8, 0xce, 0xc1, 0x6b, 0x38, 0x97, 0x2a, 0x9a, 0x24, 0xce, 0x7c, 0x9a, 0x05, 0xe9, 0x26, 0x60,
	0xaa, 0xd3, 0xe5, 0xf6, 0x90, 0x9d, 0xc1, 0xd1, 0xa3, 0x78, 0xf9, 0x2b, 0x00, 0x0b, 0x21, 0xd8,
	0x8c, 0xd8, 0x65, 0x3a, 0xf3, 0xb2, 0x12, 0xe5, 0x7f, 0x33, 0x07, 0x40, 0xac, 0xac, 0xb3, 0xc9,
	0x80, 0x3c, 0xc9, 0xaa, 0xe5, 0xc3, 0x3e, 0x21, 0x38, 0x6f, 0xaa, 0x34, 0x2e, 0x24, 0xd7, 0xa5,
	0xce, 0xdb, 0x69, 0x86, 0x2e, 0xce, 0x12, 0x20, 0xb7, 0xb2, 0x50, 0xc3, 0xb6, 0xda, 0xa4, 0x9b,
	0x18, 0x32, 0xc9, 0xbe, 0x26, 0xe0, 0xdf, 0x9b, 0xf7, 0xa5, 0x0b, 0x70, 0x35, 0x6a, 0x7a, 0xb2,
	0x25, 0x88, 0x5e, 0x2c, 0x3e, 0xfd, 0xdd, 0xee, 0x6e, 0x37, 0xa2, 0x37, 0xe0, 0x5b, 0x70, 0x74,
	0xb6, 0x9d, 0xe9, 0xd1, 0x8e, 0xa3, 0xdd, 0x83, 0x1f, 0xf9, 0x02, 0x5c, 0x8d, 0x0b, 0xef, 0x45,
	0xd4, 0xf1, 0xde, 0x1e, 0xd5, 0x11, 0xbd, 0x06, 0xcf, 0x30, 0xa2, 0x68, 0x04, 0x83, 0x8e, 0x67,
	0x3b, 0x7d, 0xac, 0x35, 0x68, 0xb0, 0x16, 0xd3, 0xc4, 0xda, 0x1e, 0x43, 0x36, 0x7a, 0xf6, 0xcd,
	0x9f, 0x70, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x07, 0xe0, 0x93, 0x3a, 0x19, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GossipClient is the client API for Gossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GossipClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Unjoin(ctx context.Context, in *UnjoinRequest, opts ...grpc.CallOption) (*UnjoinResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Erase(ctx context.Context, in *EraseRequest, opts ...grpc.CallOption) (*EraseResponse, error)
}

type gossipClient struct {
	cc *grpc.ClientConn
}

func NewGossipClient(cc *grpc.ClientConn) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/internal.Gossip/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) Unjoin(ctx context.Context, in *UnjoinRequest, opts ...grpc.CallOption) (*UnjoinResponse, error) {
	out := new(UnjoinResponse)
	err := c.cc.Invoke(ctx, "/internal.Gossip/Unjoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/internal.Gossip/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, "/internal.Gossip/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) Erase(ctx context.Context, in *EraseRequest, opts ...grpc.CallOption) (*EraseResponse, error) {
	out := new(EraseResponse)
	err := c.cc.Invoke(ctx, "/internal.Gossip/Erase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipServer is the server API for Gossip service.
type GossipServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Unjoin(context.Context, *UnjoinRequest) (*UnjoinResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Erase(context.Context, *EraseRequest) (*EraseResponse, error)
}

// UnimplementedGossipServer can be embedded to have forward compatible implementations.
type UnimplementedGossipServer struct {
}

func (*UnimplementedGossipServer) Join(ctx context.Context, req *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedGossipServer) Unjoin(ctx context.Context, req *UnjoinRequest) (*UnjoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unjoin not implemented")
}
func (*UnimplementedGossipServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedGossipServer) Write(ctx context.Context, req *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (*UnimplementedGossipServer) Erase(ctx context.Context, req *EraseRequest) (*EraseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Erase not implemented")
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Gossip/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_Unjoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnjoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Unjoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Gossip/Unjoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Unjoin(ctx, req.(*UnjoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Gossip/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Gossip/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Gossip/Erase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Erase(ctx, req.(*EraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Gossip_Join_Handler,
		},
		{
			MethodName: "Unjoin",
			Handler:    _Gossip_Unjoin_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Gossip_Ping_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Gossip_Write_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _Gossip_Erase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gossip.proto",
}
